
package ru.korus.tmis.ws.laboratory.bak.ws.server.model.hl7.complex;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PIXManager_PortType", targetNamespace = "urn:ihe:iti:pixv3:2007")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PIXManagerPortType {


    /**
     * 
     * @param body
     */
    @WebMethod(operationName = "PIXManager_PRPA_IN201301UV02", action = "urn:hl7-org:v3:PRPA_IN201301UV02")
    public void pixManagerPRPAIN201301UV02(
        @WebParam(name = "MCCI_IN000002UV01", targetNamespace = "urn:hl7-org:v3", mode = WebParam.Mode.INOUT, partName = "Body")
        Holder<MCCIIN000002UV01> body);

}
