//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.15 at 11:16:43 AM MSK 
//


package ru.korus.tmis.admin.service.impl.domain;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for admin-serviceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="admin-serviceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="jmx-connector" type="{}jmx-connectorType"/>
 *         &lt;element name="property" type="{}propertyType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="das-config" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="system-jmx-connector-name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "admin-serviceType", propOrder = {
    "jmxConnector",
    "property",
    "dasConfig"
})
public class AdminServiceType {

    @XmlElement(name = "jmx-connector", required = true)
    protected JmxConnectorType jmxConnector;
    protected List<PropertyType> property;
    @XmlElement(name = "das-config", required = true)
    protected String dasConfig;
    @XmlAttribute(name = "system-jmx-connector-name")
    protected String systemJmxConnectorName;
    @XmlAttribute(name = "type")
    protected String type;

    /**
     * Gets the value of the jmxConnector property.
     * 
     * @return
     *     possible object is
     *     {@link JmxConnectorType }
     *     
     */
    public JmxConnectorType getJmxConnector() {
        return jmxConnector;
    }

    /**
     * Sets the value of the jmxConnector property.
     * 
     * @param value
     *     allowed object is
     *     {@link JmxConnectorType }
     *     
     */
    public void setJmxConnector(JmxConnectorType value) {
        this.jmxConnector = value;
    }

    /**
     * Gets the value of the property property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the property property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProperty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PropertyType }
     * 
     * 
     */
    public List<PropertyType> getProperty() {
        if (property == null) {
            property = new ArrayList<PropertyType>();
        }
        return this.property;
    }

    /**
     * Gets the value of the dasConfig property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDasConfig() {
        return dasConfig;
    }

    /**
     * Sets the value of the dasConfig property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDasConfig(String value) {
        this.dasConfig = value;
    }

    /**
     * Gets the value of the systemJmxConnectorName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSystemJmxConnectorName() {
        return systemJmxConnectorName;
    }

    /**
     * Sets the value of the systemJmxConnectorName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSystemJmxConnectorName(String value) {
        this.systemJmxConnectorName = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

}
