//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.15 at 11:16:43 AM MSK 
//


package ru.korus.tmis.admin.service.impl.domain;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.korus.tmis.admin.service.impl.domain package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Domain_QNAME = new QName("", "domain");
    private final static QName _JaccProviderTypeProperty_QNAME = new QName("", "property");
    private final static QName _IiopListenerTypeSsl_QNAME = new QName("", "ssl");
    private final static QName _ConfigTypeAdminService_QNAME = new QName("", "admin-service");
    private final static QName _ConfigTypeEjbContainer_QNAME = new QName("", "ejb-container");
    private final static QName _ConfigTypeTransactionService_QNAME = new QName("", "transaction-service");
    private final static QName _ConfigTypeManagementRules_QNAME = new QName("", "management-rules");
    private final static QName _ConfigTypeJavaConfig_QNAME = new QName("", "java-config");
    private final static QName _ConfigTypeMonitoringService_QNAME = new QName("", "monitoring-service");
    private final static QName _ConfigTypeGroupManagementService_QNAME = new QName("", "group-management-service");
    private final static QName _ConfigTypeAvailabilityService_QNAME = new QName("", "availability-service");
    private final static QName _ConfigTypeThreadPools_QNAME = new QName("", "thread-pools");
    private final static QName _ConfigTypeWebContainer_QNAME = new QName("", "web-container");
    private final static QName _ConfigTypeMdbContainer_QNAME = new QName("", "mdb-container");
    private final static QName _ConfigTypeLogService_QNAME = new QName("", "log-service");
    private final static QName _ConfigTypeHttpService_QNAME = new QName("", "http-service");
    private final static QName _ConfigTypeJmsService_QNAME = new QName("", "jms-service");
    private final static QName _ConfigTypeConnectorService_QNAME = new QName("", "connector-service");
    private final static QName _ConfigTypeSystemProperty_QNAME = new QName("", "system-property");
    private final static QName _ConfigTypeNetworkConfig_QNAME = new QName("", "network-config");
    private final static QName _ConfigTypeIiopService_QNAME = new QName("", "iiop-service");
    private final static QName _ConfigTypeDiagnosticService_QNAME = new QName("", "diagnostic-service");
    private final static QName _ConfigTypeSecurityService_QNAME = new QName("", "security-service");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.korus.tmis.admin.service.impl.domain
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DomainType }
     * 
     */
    public DomainType createDomainType() {
        return new DomainType();
    }

    /**
     * Create an instance of {@link NetworkListenersType }
     * 
     */
    public NetworkListenersType createNetworkListenersType() {
        return new NetworkListenersType();
    }

    /**
     * Create an instance of {@link SecurityServiceType }
     * 
     */
    public SecurityServiceType createSecurityServiceType() {
        return new SecurityServiceType();
    }

    /**
     * Create an instance of {@link HttpServiceType }
     * 
     */
    public HttpServiceType createHttpServiceType() {
        return new HttpServiceType();
    }

    /**
     * Create an instance of {@link ApplicationRefType }
     * 
     */
    public ApplicationRefType createApplicationRefType() {
        return new ApplicationRefType();
    }

    /**
     * Create an instance of {@link ProtocolType }
     * 
     */
    public ProtocolType createProtocolType() {
        return new ProtocolType();
    }

    /**
     * Create an instance of {@link NodesType }
     * 
     */
    public NodesType createNodesType() {
        return new NodesType();
    }

    /**
     * Create an instance of {@link JmxConnectorType }
     * 
     */
    public JmxConnectorType createJmxConnectorType() {
        return new JmxConnectorType();
    }

    /**
     * Create an instance of {@link ApplicationType }
     * 
     */
    public ApplicationType createApplicationType() {
        return new ApplicationType();
    }

    /**
     * Create an instance of {@link GroupManagementServiceType }
     * 
     */
    public GroupManagementServiceType createGroupManagementServiceType() {
        return new GroupManagementServiceType();
    }

    /**
     * Create an instance of {@link SessionConfigType }
     * 
     */
    public SessionConfigType createSessionConfigType() {
        return new SessionConfigType();
    }

    /**
     * Create an instance of {@link SecureAdminType }
     * 
     */
    public SecureAdminType createSecureAdminType() {
        return new SecureAdminType();
    }

    /**
     * Create an instance of {@link ResponsePolicyType }
     * 
     */
    public ResponsePolicyType createResponsePolicyType() {
        return new ResponsePolicyType();
    }

    /**
     * Create an instance of {@link JdbcResourceType }
     * 
     */
    public JdbcResourceType createJdbcResourceType() {
        return new JdbcResourceType();
    }

    /**
     * Create an instance of {@link AvailabilityServiceType }
     * 
     */
    public AvailabilityServiceType createAvailabilityServiceType() {
        return new AvailabilityServiceType();
    }

    /**
     * Create an instance of {@link OrbType }
     * 
     */
    public OrbType createOrbType() {
        return new OrbType();
    }

    /**
     * Create an instance of {@link AdminObjectResourceType }
     * 
     */
    public AdminObjectResourceType createAdminObjectResourceType() {
        return new AdminObjectResourceType();
    }

    /**
     * Create an instance of {@link JmsHostType }
     * 
     */
    public JmsHostType createJmsHostType() {
        return new JmsHostType();
    }

    /**
     * Create an instance of {@link ResourcesType }
     * 
     */
    public ResourcesType createResourcesType() {
        return new ResourcesType();
    }

    /**
     * Create an instance of {@link ProtocolsType }
     * 
     */
    public ProtocolsType createProtocolsType() {
        return new ProtocolsType();
    }

    /**
     * Create an instance of {@link JaccProviderType }
     * 
     */
    public JaccProviderType createJaccProviderType() {
        return new JaccProviderType();
    }

    /**
     * Create an instance of {@link AdminServiceType }
     * 
     */
    public AdminServiceType createAdminServiceType() {
        return new AdminServiceType();
    }

    /**
     * Create an instance of {@link ThreadPoolType }
     * 
     */
    public ThreadPoolType createThreadPoolType() {
        return new ThreadPoolType();
    }

    /**
     * Create an instance of {@link TransportsType }
     * 
     */
    public TransportsType createTransportsType() {
        return new TransportsType();
    }

    /**
     * Create an instance of {@link VirtualServerType }
     * 
     */
    public VirtualServerType createVirtualServerType() {
        return new VirtualServerType();
    }

    /**
     * Create an instance of {@link EjbContainerType }
     * 
     */
    public EjbContainerType createEjbContainerType() {
        return new EjbContainerType();
    }

    /**
     * Create an instance of {@link ProviderConfigType }
     * 
     */
    public ProviderConfigType createProviderConfigType() {
        return new ProviderConfigType();
    }

    /**
     * Create an instance of {@link MessageSecurityConfigType }
     * 
     */
    public MessageSecurityConfigType createMessageSecurityConfigType() {
        return new MessageSecurityConfigType();
    }

    /**
     * Create an instance of {@link JmsServiceType }
     * 
     */
    public JmsServiceType createJmsServiceType() {
        return new JmsServiceType();
    }

    /**
     * Create an instance of {@link ConfigsType }
     * 
     */
    public ConfigsType createConfigsType() {
        return new ConfigsType();
    }

    /**
     * Create an instance of {@link ModuleType }
     * 
     */
    public ModuleType createModuleType() {
        return new ModuleType();
    }

    /**
     * Create an instance of {@link AuditModuleType }
     * 
     */
    public AuditModuleType createAuditModuleType() {
        return new AuditModuleType();
    }

    /**
     * Create an instance of {@link SessionManagerType }
     * 
     */
    public SessionManagerType createSessionManagerType() {
        return new SessionManagerType();
    }

    /**
     * Create an instance of {@link PortUnificationType }
     * 
     */
    public PortUnificationType createPortUnificationType() {
        return new PortUnificationType();
    }

    /**
     * Create an instance of {@link ThreadPoolsType }
     * 
     */
    public ThreadPoolsType createThreadPoolsType() {
        return new ThreadPoolsType();
    }

    /**
     * Create an instance of {@link ServersType }
     * 
     */
    public ServersType createServersType() {
        return new ServersType();
    }

    /**
     * Create an instance of {@link IiopServiceType }
     * 
     */
    public IiopServiceType createIiopServiceType() {
        return new IiopServiceType();
    }

    /**
     * Create an instance of {@link NetworkListenerType }
     * 
     */
    public NetworkListenerType createNetworkListenerType() {
        return new NetworkListenerType();
    }

    /**
     * Create an instance of {@link RequestPolicyType }
     * 
     */
    public RequestPolicyType createRequestPolicyType() {
        return new RequestPolicyType();
    }

    /**
     * Create an instance of {@link JavaConfigType }
     * 
     */
    public JavaConfigType createJavaConfigType() {
        return new JavaConfigType();
    }

    /**
     * Create an instance of {@link EjbContainerAvailabilityType }
     * 
     */
    public EjbContainerAvailabilityType createEjbContainerAvailabilityType() {
        return new EjbContainerAvailabilityType();
    }

    /**
     * Create an instance of {@link ProtocolFinderType }
     * 
     */
    public ProtocolFinderType createProtocolFinderType() {
        return new ProtocolFinderType();
    }

    /**
     * Create an instance of {@link SystemApplicationsType }
     * 
     */
    public SystemApplicationsType createSystemApplicationsType() {
        return new SystemApplicationsType();
    }

    /**
     * Create an instance of {@link NodeType }
     * 
     */
    public NodeType createNodeType() {
        return new NodeType();
    }

    /**
     * Create an instance of {@link ResourceRefType }
     * 
     */
    public ResourceRefType createResourceRefType() {
        return new ResourceRefType();
    }

    /**
     * Create an instance of {@link SslType }
     * 
     */
    public SslType createSslType() {
        return new SslType();
    }

    /**
     * Create an instance of {@link AuthRealmType }
     * 
     */
    public AuthRealmType createAuthRealmType() {
        return new AuthRealmType();
    }

    /**
     * Create an instance of {@link ConfigType }
     * 
     */
    public ConfigType createConfigType() {
        return new ConfigType();
    }

    /**
     * Create an instance of {@link ServerType }
     * 
     */
    public ServerType createServerType() {
        return new ServerType();
    }

    /**
     * Create an instance of {@link SecureAdminPrincipalType }
     * 
     */
    public SecureAdminPrincipalType createSecureAdminPrincipalType() {
        return new SecureAdminPrincipalType();
    }

    /**
     * Create an instance of {@link EngineType }
     * 
     */
    public EngineType createEngineType() {
        return new EngineType();
    }

    /**
     * Create an instance of {@link PropertyType }
     * 
     */
    public PropertyType createPropertyType() {
        return new PropertyType();
    }

    /**
     * Create an instance of {@link WebContainerType }
     * 
     */
    public WebContainerType createWebContainerType() {
        return new WebContainerType();
    }

    /**
     * Create an instance of {@link LogServiceType }
     * 
     */
    public LogServiceType createLogServiceType() {
        return new LogServiceType();
    }

    /**
     * Create an instance of {@link IiopListenerType }
     * 
     */
    public IiopListenerType createIiopListenerType() {
        return new IiopListenerType();
    }

    /**
     * Create an instance of {@link TransactionServiceType }
     * 
     */
    public TransactionServiceType createTransactionServiceType() {
        return new TransactionServiceType();
    }

    /**
     * Create an instance of {@link JdbcConnectionPoolType }
     * 
     */
    public JdbcConnectionPoolType createJdbcConnectionPoolType() {
        return new JdbcConnectionPoolType();
    }

    /**
     * Create an instance of {@link HttpRedirectType }
     * 
     */
    public HttpRedirectType createHttpRedirectType() {
        return new HttpRedirectType();
    }

    /**
     * Create an instance of {@link NetworkConfigType }
     * 
     */
    public NetworkConfigType createNetworkConfigType() {
        return new NetworkConfigType();
    }

    /**
     * Create an instance of {@link MonitoringServiceType }
     * 
     */
    public MonitoringServiceType createMonitoringServiceType() {
        return new MonitoringServiceType();
    }

    /**
     * Create an instance of {@link HttpType }
     * 
     */
    public HttpType createHttpType() {
        return new HttpType();
    }

    /**
     * Create an instance of {@link TransportType }
     * 
     */
    public TransportType createTransportType() {
        return new TransportType();
    }

    /**
     * Create an instance of {@link ApplicationsType }
     * 
     */
    public ApplicationsType createApplicationsType() {
        return new ApplicationsType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DomainType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "domain")
    public JAXBElement<DomainType> createDomain(DomainType value) {
        return new JAXBElement<DomainType>(_Domain_QNAME, DomainType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PropertyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "property", scope = JaccProviderType.class)
    public JAXBElement<PropertyType> createJaccProviderTypeProperty(PropertyType value) {
        return new JAXBElement<PropertyType>(_JaccProviderTypeProperty_QNAME, PropertyType.class, JaccProviderType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PropertyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "property", scope = VirtualServerType.class)
    public JAXBElement<PropertyType> createVirtualServerTypeProperty(PropertyType value) {
        return new JAXBElement<PropertyType>(_JaccProviderTypeProperty_QNAME, PropertyType.class, VirtualServerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PropertyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "property", scope = JdbcResourceType.class)
    public JAXBElement<PropertyType> createJdbcResourceTypeProperty(PropertyType value) {
        return new JAXBElement<PropertyType>(_JaccProviderTypeProperty_QNAME, PropertyType.class, JdbcResourceType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SslType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ssl", scope = IiopListenerType.class)
    public JAXBElement<SslType> createIiopListenerTypeSsl(SslType value) {
        return new JAXBElement<SslType>(_IiopListenerTypeSsl_QNAME, SslType.class, IiopListenerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PropertyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "property", scope = AuthRealmType.class)
    public JAXBElement<PropertyType> createAuthRealmTypeProperty(PropertyType value) {
        return new JAXBElement<PropertyType>(_JaccProviderTypeProperty_QNAME, PropertyType.class, AuthRealmType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdminServiceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "admin-service", scope = ConfigType.class)
    public JAXBElement<AdminServiceType> createConfigTypeAdminService(AdminServiceType value) {
        return new JAXBElement<AdminServiceType>(_ConfigTypeAdminService_QNAME, AdminServiceType.class, ConfigType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EjbContainerType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ejb-container", scope = ConfigType.class)
    public JAXBElement<EjbContainerType> createConfigTypeEjbContainer(EjbContainerType value) {
        return new JAXBElement<EjbContainerType>(_ConfigTypeEjbContainer_QNAME, EjbContainerType.class, ConfigType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TransactionServiceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "transaction-service", scope = ConfigType.class)
    public JAXBElement<TransactionServiceType> createConfigTypeTransactionService(TransactionServiceType value) {
        return new JAXBElement<TransactionServiceType>(_ConfigTypeTransactionService_QNAME, TransactionServiceType.class, ConfigType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "management-rules", scope = ConfigType.class)
    public JAXBElement<String> createConfigTypeManagementRules(String value) {
        return new JAXBElement<String>(_ConfigTypeManagementRules_QNAME, String.class, ConfigType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link JavaConfigType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "java-config", scope = ConfigType.class)
    public JAXBElement<JavaConfigType> createConfigTypeJavaConfig(JavaConfigType value) {
        return new JAXBElement<JavaConfigType>(_ConfigTypeJavaConfig_QNAME, JavaConfigType.class, ConfigType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MonitoringServiceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "monitoring-service", scope = ConfigType.class)
    public JAXBElement<MonitoringServiceType> createConfigTypeMonitoringService(MonitoringServiceType value) {
        return new JAXBElement<MonitoringServiceType>(_ConfigTypeMonitoringService_QNAME, MonitoringServiceType.class, ConfigType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GroupManagementServiceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "group-management-service", scope = ConfigType.class)
    public JAXBElement<GroupManagementServiceType> createConfigTypeGroupManagementService(GroupManagementServiceType value) {
        return new JAXBElement<GroupManagementServiceType>(_ConfigTypeGroupManagementService_QNAME, GroupManagementServiceType.class, ConfigType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AvailabilityServiceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "availability-service", scope = ConfigType.class)
    public JAXBElement<AvailabilityServiceType> createConfigTypeAvailabilityService(AvailabilityServiceType value) {
        return new JAXBElement<AvailabilityServiceType>(_ConfigTypeAvailabilityService_QNAME, AvailabilityServiceType.class, ConfigType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ThreadPoolsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "thread-pools", scope = ConfigType.class)
    public JAXBElement<ThreadPoolsType> createConfigTypeThreadPools(ThreadPoolsType value) {
        return new JAXBElement<ThreadPoolsType>(_ConfigTypeThreadPools_QNAME, ThreadPoolsType.class, ConfigType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WebContainerType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "web-container", scope = ConfigType.class)
    public JAXBElement<WebContainerType> createConfigTypeWebContainer(WebContainerType value) {
        return new JAXBElement<WebContainerType>(_ConfigTypeWebContainer_QNAME, WebContainerType.class, ConfigType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "mdb-container", scope = ConfigType.class)
    public JAXBElement<String> createConfigTypeMdbContainer(String value) {
        return new JAXBElement<String>(_ConfigTypeMdbContainer_QNAME, String.class, ConfigType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LogServiceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "log-service", scope = ConfigType.class)
    public JAXBElement<LogServiceType> createConfigTypeLogService(LogServiceType value) {
        return new JAXBElement<LogServiceType>(_ConfigTypeLogService_QNAME, LogServiceType.class, ConfigType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HttpServiceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "http-service", scope = ConfigType.class)
    public JAXBElement<HttpServiceType> createConfigTypeHttpService(HttpServiceType value) {
        return new JAXBElement<HttpServiceType>(_ConfigTypeHttpService_QNAME, HttpServiceType.class, ConfigType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link JmsServiceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "jms-service", scope = ConfigType.class)
    public JAXBElement<JmsServiceType> createConfigTypeJmsService(JmsServiceType value) {
        return new JAXBElement<JmsServiceType>(_ConfigTypeJmsService_QNAME, JmsServiceType.class, ConfigType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "connector-service", scope = ConfigType.class)
    public JAXBElement<String> createConfigTypeConnectorService(String value) {
        return new JAXBElement<String>(_ConfigTypeConnectorService_QNAME, String.class, ConfigType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PropertyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "system-property", scope = ConfigType.class)
    public JAXBElement<PropertyType> createConfigTypeSystemProperty(PropertyType value) {
        return new JAXBElement<PropertyType>(_ConfigTypeSystemProperty_QNAME, PropertyType.class, ConfigType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NetworkConfigType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "network-config", scope = ConfigType.class)
    public JAXBElement<NetworkConfigType> createConfigTypeNetworkConfig(NetworkConfigType value) {
        return new JAXBElement<NetworkConfigType>(_ConfigTypeNetworkConfig_QNAME, NetworkConfigType.class, ConfigType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IiopServiceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "iiop-service", scope = ConfigType.class)
    public JAXBElement<IiopServiceType> createConfigTypeIiopService(IiopServiceType value) {
        return new JAXBElement<IiopServiceType>(_ConfigTypeIiopService_QNAME, IiopServiceType.class, ConfigType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "diagnostic-service", scope = ConfigType.class)
    public JAXBElement<String> createConfigTypeDiagnosticService(String value) {
        return new JAXBElement<String>(_ConfigTypeDiagnosticService_QNAME, String.class, ConfigType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SecurityServiceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "security-service", scope = ConfigType.class)
    public JAXBElement<SecurityServiceType> createConfigTypeSecurityService(SecurityServiceType value) {
        return new JAXBElement<SecurityServiceType>(_ConfigTypeSecurityService_QNAME, SecurityServiceType.class, ConfigType.class, value);
    }

}
