//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.15 at 11:16:43 AM MSK 
//


package ru.korus.tmis.admin.service.impl.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for protocolType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="protocolType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="http" type="{}httpType" minOccurs="0"/>
 *         &lt;element name="ssl" type="{}sslType" minOccurs="0"/>
 *         &lt;element name="http-redirect" type="{}http-redirectType" minOccurs="0"/>
 *         &lt;element name="port-unification" type="{}port-unificationType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="security-enabled" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "protocolType", propOrder = {
    "http",
    "ssl",
    "httpRedirect",
    "portUnification"
})
public class ProtocolType {

    protected HttpType http;
    protected SslType ssl;
    @XmlElement(name = "http-redirect")
    protected HttpRedirectType httpRedirect;
    @XmlElement(name = "port-unification")
    protected PortUnificationType portUnification;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "security-enabled")
    protected String securityEnabled;

    /**
     * Gets the value of the http property.
     * 
     * @return
     *     possible object is
     *     {@link HttpType }
     *     
     */
    public HttpType getHttp() {
        return http;
    }

    /**
     * Sets the value of the http property.
     * 
     * @param value
     *     allowed object is
     *     {@link HttpType }
     *     
     */
    public void setHttp(HttpType value) {
        this.http = value;
    }

    /**
     * Gets the value of the ssl property.
     * 
     * @return
     *     possible object is
     *     {@link SslType }
     *     
     */
    public SslType getSsl() {
        return ssl;
    }

    /**
     * Sets the value of the ssl property.
     * 
     * @param value
     *     allowed object is
     *     {@link SslType }
     *     
     */
    public void setSsl(SslType value) {
        this.ssl = value;
    }

    /**
     * Gets the value of the httpRedirect property.
     * 
     * @return
     *     possible object is
     *     {@link HttpRedirectType }
     *     
     */
    public HttpRedirectType getHttpRedirect() {
        return httpRedirect;
    }

    /**
     * Sets the value of the httpRedirect property.
     * 
     * @param value
     *     allowed object is
     *     {@link HttpRedirectType }
     *     
     */
    public void setHttpRedirect(HttpRedirectType value) {
        this.httpRedirect = value;
    }

    /**
     * Gets the value of the portUnification property.
     * 
     * @return
     *     possible object is
     *     {@link PortUnificationType }
     *     
     */
    public PortUnificationType getPortUnification() {
        return portUnification;
    }

    /**
     * Sets the value of the portUnification property.
     * 
     * @param value
     *     allowed object is
     *     {@link PortUnificationType }
     *     
     */
    public void setPortUnification(PortUnificationType value) {
        this.portUnification = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the securityEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecurityEnabled() {
        return securityEnabled;
    }

    /**
     * Sets the value of the securityEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecurityEnabled(String value) {
        this.securityEnabled = value;
    }

}
