package ru.korus.tmis.ws.transfusion.devtest.wsimport;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.4-b01 Generated source version: 2.2
 * 
 */
@WebService(name = "TransfusionService", targetNamespace = "http://korus.ru/tmis/ws/transfusion")
@XmlSeeAlso({ ObjectFactory.class })
public interface TransfusionService {

    /**
     * 
     * @return returns java.dbutil.List<ru.korus.tmis.ws.transfusion.devtest.wsimport.DivisionInfo>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDivisions", targetNamespace = "http://korus.ru/tmis/ws/transfusion",
            className = "ru.korus.tmis.ws.transfusion.devtest.wsimport.GetDivisions")
    @ResponseWrapper(localName = "getDivisionsResponse", targetNamespace = "http://korus.ru/tmis/ws/transfusion",
            className = "ru.korus.tmis.ws.transfusion.devtest.wsimport.GetDivisionsResponse")
    @Action(input = "http://korus.ru/tmis/ws/transfusion/TransfusionService/getDivisionsRequest",
            output = "http://korus.ru/tmis/ws/transfusion/TransfusionService/getDivisionsResponse")
    public List<DivisionInfo> getDivisions();

    /**
     * 
     * @param factDate
     * @param requestId
     * @param orderComment
     * @param components
     * @return returns ru.korus.tmis.ws.transfusion.devtest.wsimport.IssueResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setOrderIssueResult", targetNamespace = "http://korus.ru/tmis/ws/transfusion",
            className = "ru.korus.tmis.ws.transfusion.devtest.wsimport.SetOrderIssueResult")
    @ResponseWrapper(localName = "setOrderIssueResultResponse", targetNamespace = "http://korus.ru/tmis/ws/transfusion",
            className = "ru.korus.tmis.ws.transfusion.devtest.wsimport.SetOrderIssueResultResponse")
    @Action(input = "http://korus.ru/tmis/ws/transfusion/TransfusionService/setOrderIssueResultRequest",
            output = "http://korus.ru/tmis/ws/transfusion/TransfusionService/setOrderIssueResultResponse")
    public IssueResult setOrderIssueResult(@WebParam(name = "requestId", targetNamespace = "http://korus.ru/tmis/ws/transfusion") Integer requestId, @WebParam(
            name = "factDate", targetNamespace = "http://korus.ru/tmis/ws/transfusion") XMLGregorianCalendar factDate, @WebParam(name = "components",
            targetNamespace = "http://korus.ru/tmis/ws/transfusion") List<OrderIssueInfo> components, @WebParam(name = "orderComment",
            targetNamespace = "http://korus.ru/tmis/ws/transfusion") String orderComment);

    /**
     * 
     * @param eritrocyteMass
     * @param finalVolumeList
     * @param patientCredentials
     * @param measures
     * @param procedureInfo
     * @return returns ru.korus.tmis.ws.transfusion.devtest.wsimport.IssueResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setProcedureResult", targetNamespace = "http://korus.ru/tmis/ws/transfusion",
            className = "ru.korus.tmis.ws.transfusion.devtest.wsimport.SetProcedureResult")
    @ResponseWrapper(localName = "setProcedureResultResponse", targetNamespace = "http://korus.ru/tmis/ws/transfusion",
            className = "ru.korus.tmis.ws.transfusion.devtest.wsimport.SetProcedureResultResponse")
    @Action(input = "http://korus.ru/tmis/ws/transfusion/TransfusionService/setProcedureResultRequest",
            output = "http://korus.ru/tmis/ws/transfusion/TransfusionService/setProcedureResultResponse")
    public IssueResult
            setProcedureResult(@WebParam(name = "patientCredentials", targetNamespace = "http://korus.ru/tmis/ws/transfusion") PatientCredentials patientCredentials,
                    @WebParam(name = "ProcedureInfo", targetNamespace = "http://korus.ru/tmis/ws/transfusion") ProcedureInfo procedureInfo,
                    @WebParam(name = "EritrocyteMass", targetNamespace = "http://korus.ru/tmis/ws/transfusion") EritrocyteMass eritrocyteMass,
                    @WebParam(name = "Measures", targetNamespace = "http://korus.ru/tmis/ws/transfusion") List<LaboratoryMeasure> measures,
                    @WebParam(name = "finalVolumeList", targetNamespace = "http://korus.ru/tmis/ws/transfusion") List<FinalVolume> finalVolumeList);

}
