//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.16 at 03:07:22 PM MSD 
//


package org.hl7.v3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for POCD_MT000040.Reference complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="POCD_MT000040.Reference">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="realmCode" type="{urn:hl7-org:v3}CS" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="typeId" type="{urn:hl7-org:v3}POCD_MT000040.InfrastructureRoot.typeId" minOccurs="0"/>
 *         &lt;element name="templateId" type="{urn:hl7-org:v3}II" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="seperatableInd" type="{urn:hl7-org:v3}BL" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element name="externalAct" type="{urn:hl7-org:v3}POCD_MT000040.ExternalAct"/>
 *           &lt;element name="externalObservation" type="{urn:hl7-org:v3}POCD_MT000040.ExternalObservation"/>
 *           &lt;element name="externalProcedure" type="{urn:hl7-org:v3}POCD_MT000040.ExternalProcedure"/>
 *           &lt;element name="externalDocument" type="{urn:hl7-org:v3}POCD_MT000040.ExternalDocument"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="nullFlavor" type="{urn:hl7-org:v3}NullFlavor" />
 *       &lt;attribute name="typeCode" use="required" type="{urn:hl7-org:v3}x_ActRelationshipExternalReference" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "POCD_MT000040.Reference", propOrder = {
        "realmCode",
        "typeId",
        "templateId",
        "seperatableInd",
        "externalAct",
        "externalObservation",
        "externalProcedure",
        "externalDocument"
})
public class PocdReference {

    protected List<CS> realmCode;
    protected PocdInfrastructureRootTypeId typeId;
    protected List<II> templateId;
    protected BL seperatableInd;
    protected PocdExternalAct externalAct;
    protected PocdExternalObservation externalObservation;
    protected PocdExternalProcedure externalProcedure;
    protected PocdExternalDocument externalDocument;
    @XmlAttribute
    protected List<String> nullFlavor;
    @XmlAttribute(required = true)
    protected XActRelationshipExternalReference typeCode;

    /**
     * Gets the value of the realmCode property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the realmCode property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRealmCode().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link CS }
     */
    public List<CS> getRealmCode() {
        if (realmCode == null) {
            realmCode = new ArrayList<CS>();
        }
        return this.realmCode;
    }

    /**
     * Gets the value of the typeId property.
     *
     * @return possible object is
     *         {@link PocdInfrastructureRootTypeId }
     */
    public PocdInfrastructureRootTypeId getTypeId() {
        return typeId;
    }

    /**
     * Sets the value of the typeId property.
     *
     * @param value allowed object is
     *              {@link PocdInfrastructureRootTypeId }
     */
    public void setTypeId(PocdInfrastructureRootTypeId value) {
        this.typeId = value;
    }

    /**
     * Gets the value of the templateId property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the templateId property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTemplateId().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link II }
     */
    public List<II> getTemplateId() {
        if (templateId == null) {
            templateId = new ArrayList<II>();
        }
        return this.templateId;
    }

    /**
     * Gets the value of the seperatableInd property.
     *
     * @return possible object is
     *         {@link BL }
     */
    public BL getSeperatableInd() {
        return seperatableInd;
    }

    /**
     * Sets the value of the seperatableInd property.
     *
     * @param value allowed object is
     *              {@link BL }
     */
    public void setSeperatableInd(BL value) {
        this.seperatableInd = value;
    }

    /**
     * Gets the value of the externalAct property.
     *
     * @return possible object is
     *         {@link PocdExternalAct }
     */
    public PocdExternalAct getExternalAct() {
        return externalAct;
    }

    /**
     * Sets the value of the externalAct property.
     *
     * @param value allowed object is
     *              {@link PocdExternalAct }
     */
    public void setExternalAct(PocdExternalAct value) {
        this.externalAct = value;
    }

    /**
     * Gets the value of the externalObservation property.
     *
     * @return possible object is
     *         {@link PocdExternalObservation }
     */
    public PocdExternalObservation getExternalObservation() {
        return externalObservation;
    }

    /**
     * Sets the value of the externalObservation property.
     *
     * @param value allowed object is
     *              {@link PocdExternalObservation }
     */
    public void setExternalObservation(PocdExternalObservation value) {
        this.externalObservation = value;
    }

    /**
     * Gets the value of the externalProcedure property.
     *
     * @return possible object is
     *         {@link PocdExternalProcedure }
     */
    public PocdExternalProcedure getExternalProcedure() {
        return externalProcedure;
    }

    /**
     * Sets the value of the externalProcedure property.
     *
     * @param value allowed object is
     *              {@link PocdExternalProcedure }
     */
    public void setExternalProcedure(PocdExternalProcedure value) {
        this.externalProcedure = value;
    }

    /**
     * Gets the value of the externalDocument property.
     *
     * @return possible object is
     *         {@link PocdExternalDocument }
     */
    public PocdExternalDocument getExternalDocument() {
        return externalDocument;
    }

    /**
     * Sets the value of the externalDocument property.
     *
     * @param value allowed object is
     *              {@link PocdExternalDocument }
     */
    public void setExternalDocument(PocdExternalDocument value) {
        this.externalDocument = value;
    }

    /**
     * Gets the value of the nullFlavor property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nullFlavor property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNullFlavor().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     */
    public List<String> getNullFlavor() {
        if (nullFlavor == null) {
            nullFlavor = new ArrayList<String>();
        }
        return this.nullFlavor;
    }

    /**
     * Gets the value of the typeCode property.
     *
     * @return possible object is
     *         {@link XActRelationshipExternalReference }
     */
    public XActRelationshipExternalReference getTypeCode() {
        return typeCode;
    }

    /**
     * Sets the value of the typeCode property.
     *
     * @param value allowed object is
     *              {@link XActRelationshipExternalReference }
     */
    public void setTypeCode(XActRelationshipExternalReference value) {
        this.typeCode = value;
    }

}
