
package ru.korus.tmis.laboratory.bak.ws.client;

import ru.korus.tmis.core.exception.CoreException;
import ru.korus.tmis.laboratory.bak.BakSendService;
import ru.korus.tmis.scala.util.ConfigManager;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.Authenticator;
import java.net.MalformedURLException;
import java.net.PasswordAuthentication;
import java.net.URL;
import java.util.Map;


/**
 * WSDL File for cgmsoap HL7 edition
 * <p/>
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 */
@WebServiceClient(name = "CGM_SOAP",
        targetNamespace = "http://cgm.ru",
        wsdlLocation = "../../../../../../../CGMSERVICE_hl7.wsdl")
public class BakSend extends Service {

    private final static URL CGMSOAP_WSDL_LOCATION;
    private final static WebServiceException CGMSOAP_EXCEPTION;
    private final static QName CGMSOAP_QNAME = new QName("http://cgm.ru", "CGM_SOAP");
    public final static String CGM_BAK_URL_SYSTEM_PROPERTY = "bak.intergation.url";

    static {
        final String login = ConfigManager.LaboratoryBak().User();
        final String password = ConfigManager.LaboratoryBak().Password();

        if (login != null && password != null) {
            Authenticator.setDefault(new Authenticator() {
                @Override
                protected PasswordAuthentication getPasswordAuthentication() {
                    return new PasswordAuthentication(
                            login,
                            password.toCharArray());
                }
            });
        }

        URL url = null;
        WebServiceException e = null;

        try {
            final URL baseUrl = BakSend.class.getResource("");
            url = new URL(baseUrl, "../../../../../../../CGMSERVICE_hl7.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CGMSOAP_WSDL_LOCATION = url;
        CGMSOAP_EXCEPTION = e;
    }

    public BakSend() {
        super(__getWsdlLocation(), CGMSOAP_QNAME);
    }

    public BakSend(WebServiceFeature... features) {
        super(__getWsdlLocation(), CGMSOAP_QNAME, features);
    }

    public BakSend(URL wsdlLocation) {
        super(wsdlLocation, CGMSOAP_QNAME);
    }

    public BakSend(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CGMSOAP_QNAME, features);
    }

    public BakSend(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BakSend(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * @return returns BakSend
     */
    @WebEndpoint(name = "cgmsoap_PortType")
    public BakSendService getService() throws CoreException {
        final BakSendService service
                = super.getPort(new QName("http://cgm.ru", "cgmsoap_PortType"), BakSendService.class);
        configureServiceURL((BindingProvider) service);
        return service;
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns BakSend
     */
    @WebEndpoint(name = "cgmsoap_PortType")
    public BakSendService getService(WebServiceFeature... features) throws CoreException {
        final BakSendService service
                = super.getPort(new QName("http://cgm.ru", "cgmsoap_PortType"), BakSendService.class, features);
        configureServiceURL((BindingProvider) service);
        return service;
    }

    /**
     * Получаем URL до сервиса CGM
     *
     * @param service - объект сервиса, в который установим URL
     */
    private static void configureServiceURL(BindingProvider service) throws CoreException {
        final String serviceUrl = System.getProperty(CGM_BAK_URL_SYSTEM_PROPERTY);
        if (serviceUrl != null) {
            Map<String, Object> requestContext = service.getRequestContext();
            requestContext.put(BindingProvider.ENDPOINT_ADDRESS_PROPERTY, serviceUrl);
        } else
            throw new CoreException("No system property [" + CGM_BAK_URL_SYSTEM_PROPERTY +"]");
    }

    private static URL __getWsdlLocation() {
        if (CGMSOAP_EXCEPTION != null) {
            throw CGMSOAP_EXCEPTION;
        }
        return CGMSOAP_WSDL_LOCATION;
    }

}
