
package ru.korus.tmis.pix.sda.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-2b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EMRReceiverService", targetNamespace = "urn:wsdl", wsdlLocation = "file:/C:/Project/tmis-core/core/referencebook/src/main/resources/PIX/wsdl/sda.wsdl")
public class EMRReceiverService
    extends Service
{

    private final static URL EMRRECEIVERSERVICE_WSDL_LOCATION;
    private final static WebServiceException EMRRECEIVERSERVICE_EXCEPTION;
    private final static QName EMRRECEIVERSERVICE_QNAME = new QName("urn:wsdl", "EMRReceiverService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Project/tmis-core/core/referencebook/src/main/resources/PIX/wsdl/sda.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EMRRECEIVERSERVICE_WSDL_LOCATION = url;
        EMRRECEIVERSERVICE_EXCEPTION = e;
    }

    public EMRReceiverService() {
        super(__getWsdlLocation(), EMRRECEIVERSERVICE_QNAME);
    }

    public EMRReceiverService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EMRRECEIVERSERVICE_QNAME, features);
    }

    public EMRReceiverService(URL wsdlLocation) {
        super(wsdlLocation, EMRRECEIVERSERVICE_QNAME);
    }

    public EMRReceiverService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EMRRECEIVERSERVICE_QNAME, features);
    }

    public EMRReceiverService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EMRReceiverService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EMRReceiverServiceSoap
     */
    @WebEndpoint(name = "EMRReceiverServiceSoap")
    public EMRReceiverServiceSoap getEMRReceiverServiceSoap() {
        return super.getPort(new QName("urn:wsdl", "EMRReceiverServiceSoap"), EMRReceiverServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EMRReceiverServiceSoap
     */
    @WebEndpoint(name = "EMRReceiverServiceSoap")
    public EMRReceiverServiceSoap getEMRReceiverServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("urn:wsdl", "EMRReceiverServiceSoap"), EMRReceiverServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EMRRECEIVERSERVICE_EXCEPTION!= null) {
            throw EMRRECEIVERSERVICE_EXCEPTION;
        }
        return EMRRECEIVERSERVICE_WSDL_LOCATION;
    }

}
