INSERT IGNORE INTO `rbAcheResult` (`id`, `eventPurpose_id`, `code`, `name`) VALUES (1, 8, '101', 'Выздоровление');
INSERT IGNORE INTO `rbAcheResult` (`id`, `eventPurpose_id`, `code`, `name`) VALUES (2, 8, '102', 'Улучшение');
INSERT IGNORE INTO `rbAcheResult` (`id`, `eventPurpose_id`, `code`, `name`) VALUES (3, 8, '103', 'Без перемен');
INSERT IGNORE INTO `rbAcheResult` (`id`, `eventPurpose_id`, `code`, `name`) VALUES (4, 8, '104', 'Ухудшение');
INSERT IGNORE INTO `rbAcheResult` (`id`, `eventPurpose_id`, `code`, `name`) VALUES (5, 9, '201', 'Выздоровление');
INSERT IGNORE INTO `rbAcheResult` (`id`, `eventPurpose_id`, `code`, `name`) VALUES (6, 9, '202', 'Улучшение');
INSERT IGNORE INTO `rbAcheResult` (`id`, `eventPurpose_id`, `code`, `name`) VALUES (7, 9, '203', 'Без перемен');
INSERT IGNORE INTO `rbAcheResult` (`id`, `eventPurpose_id`, `code`, `name`) VALUES (8, 9, '204', 'Ухудшение');
INSERT IGNORE INTO `rbAcheResult` (`id`, `eventPurpose_id`, `code`, `name`) VALUES (9, 2, '301', 'Выздоровление');
INSERT IGNORE INTO `rbAcheResult` (`id`, `eventPurpose_id`, `code`, `name`) VALUES (10, 2, '302', 'Ремиссия');
INSERT IGNORE INTO `rbAcheResult` (`id`, `eventPurpose_id`, `code`, `name`) VALUES (11, 2, '303', 'Улучшение');
INSERT IGNORE INTO `rbAcheResult` (`id`, `eventPurpose_id`, `code`, `name`) VALUES (12, 2, '304', 'Без перемен');
INSERT IGNORE INTO `rbAcheResult` (`id`, `eventPurpose_id`, `code`, `name`) VALUES (13, 2, '305', 'Ухудшение');
INSERT IGNORE INTO `rbAcheResult` (`id`, `eventPurpose_id`, `code`, `name`) VALUES (14, 3, '301', 'Выздоровление');
INSERT IGNORE INTO `rbAcheResult` (`id`, `eventPurpose_id`, `code`, `name`) VALUES (15, 3, '302', 'Ремиссия');
INSERT IGNORE INTO `rbAcheResult` (`id`, `eventPurpose_id`, `code`, `name`) VALUES (16, 3, '303', 'Улучшение');
INSERT IGNORE INTO `rbAcheResult` (`id`, `eventPurpose_id`, `code`, `name`) VALUES (17, 3, '304', 'Без перемен');
INSERT IGNORE INTO `rbAcheResult` (`id`, `eventPurpose_id`, `code`, `name`) VALUES (18, 3, '305', 'Ухудшение');
INSERT IGNORE INTO `rbAcheResult` (`id`, `eventPurpose_id`, `code`, `name`) VALUES (19, 10, '401', 'Улучшение');
INSERT IGNORE INTO `rbAcheResult` (`id`, `eventPurpose_id`, `code`, `name`) VALUES (20, 10, '402', 'Без эффекта');
INSERT IGNORE INTO `rbAcheResult` (`id`, `eventPurpose_id`, `code`, `name`) VALUES (21, 10, '403', 'Ухудшение');
INSERT IGNORE INTO `rbAcheResult` (`id`, `eventPurpose_id`, `code`, `name`) VALUES (22, 2, '306', 'Осмотр');
INSERT IGNORE INTO `rbAcheResult` (`id`, `eventPurpose_id`, `code`, `name`) VALUES (23, 3, '306', 'Осмотр');
INSERT IGNORE INTO `rbAcheResult` (`id`, `eventPurpose_id`, `code`, `name`) VALUES (24, 11, '301', 'Выздоровление');
INSERT IGNORE INTO `rbAcheResult` (`id`, `eventPurpose_id`, `code`, `name`) VALUES (25, 11, '302', 'Ремиссия');
INSERT IGNORE INTO `rbAcheResult` (`id`, `eventPurpose_id`, `code`, `name`) VALUES (26, 11, '303', 'Улучшение');
INSERT IGNORE INTO `rbAcheResult` (`id`, `eventPurpose_id`, `code`, `name`) VALUES (27, 11, '304', 'Без перемен');
INSERT IGNORE INTO `rbAcheResult` (`id`, `eventPurpose_id`, `code`, `name`) VALUES (28, 11, '305', 'Ухудшение');
INSERT IGNORE INTO `rbAcheResult` (`id`, `eventPurpose_id`, `code`, `name`) VALUES (29, 11, '306', 'Осмотр');
INSERT IGNORE INTO `rbAcheResult` (`id`, `eventPurpose_id`, `code`, `name`) VALUES (30, 12, '301', 'Выздоровление');
INSERT IGNORE INTO `rbAcheResult` (`id`, `eventPurpose_id`, `code`, `name`) VALUES (31, 12, '302', 'Ремиссия');
INSERT IGNORE INTO `rbAcheResult` (`id`, `eventPurpose_id`, `code`, `name`) VALUES (32, 12, '303', 'Улучшение');
INSERT IGNORE INTO `rbAcheResult` (`id`, `eventPurpose_id`, `code`, `name`) VALUES (33, 12, '304', 'Без перемен');
INSERT IGNORE INTO `rbAcheResult` (`id`, `eventPurpose_id`, `code`, `name`) VALUES (34, 12, '305', 'Ухудшение');
INSERT IGNORE INTO `rbAcheResult` (`id`, `eventPurpose_id`, `code`, `name`) VALUES (35, 12, '306', 'Осмотр');
INSERT IGNORE INTO `rbAcheResult` (`id`, `eventPurpose_id`, `code`, `name`) VALUES (36, 13, '301', 'Выздоровление');
INSERT IGNORE INTO `rbAcheResult` (`id`, `eventPurpose_id`, `code`, `name`) VALUES (37, 13, '302', 'Ремиссия');
INSERT IGNORE INTO `rbAcheResult` (`id`, `eventPurpose_id`, `code`, `name`) VALUES (38, 13, '303', 'Улучшение');
INSERT IGNORE INTO `rbAcheResult` (`id`, `eventPurpose_id`, `code`, `name`) VALUES (39, 13, '304', 'Без перемен');
INSERT IGNORE INTO `rbAcheResult` (`id`, `eventPurpose_id`, `code`, `name`) VALUES (40, 13, '305', 'Ухудшение');
INSERT IGNORE INTO `rbAcheResult` (`id`, `eventPurpose_id`, `code`, `name`) VALUES (41, 13, '306', 'Осмотр');
INSERT IGNORE INTO `rbAcheResult` (`id`, `eventPurpose_id`, `code`, `name`) VALUES (42, 14, '301', 'Выздоровление');
INSERT IGNORE INTO `rbAcheResult` (`id`, `eventPurpose_id`, `code`, `name`) VALUES (43, 14, '302', 'Ремиссия');
INSERT IGNORE INTO `rbAcheResult` (`id`, `eventPurpose_id`, `code`, `name`) VALUES (44, 14, '303', 'Улучшение');
INSERT IGNORE INTO `rbAcheResult` (`id`, `eventPurpose_id`, `code`, `name`) VALUES (45, 14, '304', 'Без перемен');
INSERT IGNORE INTO `rbAcheResult` (`id`, `eventPurpose_id`, `code`, `name`) VALUES (46, 14, '305', 'Ухудшение');
INSERT IGNORE INTO `rbAcheResult` (`id`, `eventPurpose_id`, `code`, `name`) VALUES (47, 14, '306', 'Осмотр');
INSERT IGNORE INTO `rbAcheResult` (`id`, `eventPurpose_id`, `code`, `name`) VALUES (48, 15, '301', 'Выздоровление');
INSERT IGNORE INTO `rbAcheResult` (`id`, `eventPurpose_id`, `code`, `name`) VALUES (49, 15, '302', 'Ремиссия');
INSERT IGNORE INTO `rbAcheResult` (`id`, `eventPurpose_id`, `code`, `name`) VALUES (50, 15, '303', 'Улучшение');
INSERT IGNORE INTO `rbAcheResult` (`id`, `eventPurpose_id`, `code`, `name`) VALUES (51, 15, '304', 'Без перемен');
INSERT IGNORE INTO `rbAcheResult` (`id`, `eventPurpose_id`, `code`, `name`) VALUES (52, 15, '305', 'Ухудшение');
INSERT IGNORE INTO `rbAcheResult` (`id`, `eventPurpose_id`, `code`, `name`) VALUES (53, 15, '306', 'Осмотр');
INSERT IGNORE INTO `rbAcheResult` (`id`, `eventPurpose_id`, `code`, `name`) VALUES (54, 16, '301', 'Выздоровление');
INSERT IGNORE INTO `rbAcheResult` (`id`, `eventPurpose_id`, `code`, `name`) VALUES (55, 16, '302', 'Ремиссия');
INSERT IGNORE INTO `rbAcheResult` (`id`, `eventPurpose_id`, `code`, `name`) VALUES (56, 16, '303', 'Улучшение');
INSERT IGNORE INTO `rbAcheResult` (`id`, `eventPurpose_id`, `code`, `name`) VALUES (57, 16, '304', 'Без перемен');
INSERT IGNORE INTO `rbAcheResult` (`id`, `eventPurpose_id`, `code`, `name`) VALUES (58, 16, '305', 'Ухудшение');
INSERT IGNORE INTO `rbAcheResult` (`id`, `eventPurpose_id`, `code`, `name`) VALUES (59, 16, '306', 'Осмотр');
INSERT IGNORE INTO `rbAcheResult` (`id`, `eventPurpose_id`, `code`, `name`) VALUES (60, 17, '301', 'Выздоровление');
INSERT IGNORE INTO `rbAcheResult` (`id`, `eventPurpose_id`, `code`, `name`) VALUES (61, 17, '302', 'Ремиссия');
INSERT IGNORE INTO `rbAcheResult` (`id`, `eventPurpose_id`, `code`, `name`) VALUES (62, 17, '303', 'Улучшение');
INSERT IGNORE INTO `rbAcheResult` (`id`, `eventPurpose_id`, `code`, `name`) VALUES (63, 17, '304', 'Без перемен');
INSERT IGNORE INTO `rbAcheResult` (`id`, `eventPurpose_id`, `code`, `name`) VALUES (64, 17, '305', 'Ухудшение');
INSERT IGNORE INTO `rbAcheResult` (`id`, `eventPurpose_id`, `code`, `name`) VALUES (65, 17, '306', 'Осмотр');
INSERT IGNORE INTO `rbAcheResult` (`id`, `eventPurpose_id`, `code`, `name`) VALUES (66, 18, '301', 'Выздоровление');
INSERT IGNORE INTO `rbAcheResult` (`id`, `eventPurpose_id`, `code`, `name`) VALUES (67, 18, '302', 'Ремиссия');
INSERT IGNORE INTO `rbAcheResult` (`id`, `eventPurpose_id`, `code`, `name`) VALUES (68, 18, '303', 'Улучшение');
INSERT IGNORE INTO `rbAcheResult` (`id`, `eventPurpose_id`, `code`, `name`) VALUES (69, 18, '304', 'Без перемен');
INSERT IGNORE INTO `rbAcheResult` (`id`, `eventPurpose_id`, `code`, `name`) VALUES (70, 18, '305', 'Ухудшение');
INSERT IGNORE INTO `rbAcheResult` (`id`, `eventPurpose_id`, `code`, `name`) VALUES (71, 18, '306', 'Осмотр');
