/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package ru.korus.tmis.prescription.thservice;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Базовая структура листа назначений, включает в себя список отдельных назначений
 */
public class PrescriptionList implements org.apache.thrift.TBase<PrescriptionList, PrescriptionList._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("PrescriptionList");

  private static final org.apache.thrift.protocol.TField PRESCRIPTION_LIST_FIELD_DESC = new org.apache.thrift.protocol.TField("prescriptionList", org.apache.thrift.protocol.TType.LIST, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new PrescriptionListStandardSchemeFactory());
    schemes.put(TupleScheme.class, new PrescriptionListTupleSchemeFactory());
  }

  public List<Prescription> prescriptionList; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    PRESCRIPTION_LIST((short)1, "prescriptionList");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // PRESCRIPTION_LIST
          return PRESCRIPTION_LIST;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.PRESCRIPTION_LIST, new org.apache.thrift.meta_data.FieldMetaData("prescriptionList", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Prescription.class))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(PrescriptionList.class, metaDataMap);
  }

  public PrescriptionList() {
  }

  public PrescriptionList(
    List<Prescription> prescriptionList)
  {
    this();
    this.prescriptionList = prescriptionList;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public PrescriptionList(PrescriptionList other) {
    if (other.isSetPrescriptionList()) {
      List<Prescription> __this__prescriptionList = new ArrayList<Prescription>();
      for (Prescription other_element : other.prescriptionList) {
        __this__prescriptionList.add(new Prescription(other_element));
      }
      this.prescriptionList = __this__prescriptionList;
    }
  }

  public PrescriptionList deepCopy() {
    return new PrescriptionList(this);
  }

  @Override
  public void clear() {
    this.prescriptionList = null;
  }

  public int getPrescriptionListSize() {
    return (this.prescriptionList == null) ? 0 : this.prescriptionList.size();
  }

  public java.util.Iterator<Prescription> getPrescriptionListIterator() {
    return (this.prescriptionList == null) ? null : this.prescriptionList.iterator();
  }

  public void addToPrescriptionList(Prescription elem) {
    if (this.prescriptionList == null) {
      this.prescriptionList = new ArrayList<Prescription>();
    }
    this.prescriptionList.add(elem);
  }

  public List<Prescription> getPrescriptionList() {
    return this.prescriptionList;
  }

  public PrescriptionList setPrescriptionList(List<Prescription> prescriptionList) {
    this.prescriptionList = prescriptionList;
    return this;
  }

  public void unsetPrescriptionList() {
    this.prescriptionList = null;
  }

  /** Returns true if field prescriptionList is set (has been assigned a value) and false otherwise */
  public boolean isSetPrescriptionList() {
    return this.prescriptionList != null;
  }

  public void setPrescriptionListIsSet(boolean value) {
    if (!value) {
      this.prescriptionList = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case PRESCRIPTION_LIST:
      if (value == null) {
        unsetPrescriptionList();
      } else {
        setPrescriptionList((List<Prescription>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case PRESCRIPTION_LIST:
      return getPrescriptionList();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case PRESCRIPTION_LIST:
      return isSetPrescriptionList();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof PrescriptionList)
      return this.equals((PrescriptionList)that);
    return false;
  }

  public boolean equals(PrescriptionList that) {
    if (that == null)
      return false;

    boolean this_present_prescriptionList = true && this.isSetPrescriptionList();
    boolean that_present_prescriptionList = true && that.isSetPrescriptionList();
    if (this_present_prescriptionList || that_present_prescriptionList) {
      if (!(this_present_prescriptionList && that_present_prescriptionList))
        return false;
      if (!this.prescriptionList.equals(that.prescriptionList))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(PrescriptionList other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    PrescriptionList typedOther = (PrescriptionList)other;

    lastComparison = Boolean.valueOf(isSetPrescriptionList()).compareTo(typedOther.isSetPrescriptionList());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPrescriptionList()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.prescriptionList, typedOther.prescriptionList);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("PrescriptionList(");
    boolean first = true;

    sb.append("prescriptionList:");
    if (this.prescriptionList == null) {
      sb.append("null");
    } else {
      sb.append(this.prescriptionList);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (prescriptionList == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'prescriptionList' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class PrescriptionListStandardSchemeFactory implements SchemeFactory {
    public PrescriptionListStandardScheme getScheme() {
      return new PrescriptionListStandardScheme();
    }
  }

  private static class PrescriptionListStandardScheme extends StandardScheme<PrescriptionList> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, PrescriptionList struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // PRESCRIPTION_LIST
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list24 = iprot.readListBegin();
                struct.prescriptionList = new ArrayList<Prescription>(_list24.size);
                for (int _i25 = 0; _i25 < _list24.size; ++_i25)
                {
                  Prescription _elem26; // required
                  _elem26 = new Prescription();
                  _elem26.read(iprot);
                  struct.prescriptionList.add(_elem26);
                }
                iprot.readListEnd();
              }
              struct.setPrescriptionListIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, PrescriptionList struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.prescriptionList != null) {
        oprot.writeFieldBegin(PRESCRIPTION_LIST_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.prescriptionList.size()));
          for (Prescription _iter27 : struct.prescriptionList)
          {
            _iter27.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class PrescriptionListTupleSchemeFactory implements SchemeFactory {
    public PrescriptionListTupleScheme getScheme() {
      return new PrescriptionListTupleScheme();
    }
  }

  private static class PrescriptionListTupleScheme extends TupleScheme<PrescriptionList> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, PrescriptionList struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      {
        oprot.writeI32(struct.prescriptionList.size());
        for (Prescription _iter28 : struct.prescriptionList)
        {
          _iter28.write(oprot);
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, PrescriptionList struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      {
        org.apache.thrift.protocol.TList _list29 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
        struct.prescriptionList = new ArrayList<Prescription>(_list29.size);
        for (int _i30 = 0; _i30 < _list29.size; ++_i30)
        {
          Prescription _elem31; // required
          _elem31 = new Prescription();
          _elem31.read(iprot);
          struct.prescriptionList.add(_elem31);
        }
      }
      struct.setPrescriptionListIsSet(true);
    }
  }

}

