/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package ru.korus.tmis.tfoms.thriftgen;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum PersonOptionalFields implements org.apache.thrift.TEnum {
  SNILS(0),
  MR(1),
  OKATOG(2),
  OKATOP(3),
  FAM_P(4),
  IM_P(5),
  OT_P(6),
  DR_P(7),
  W_P(8);

  private final int value;

  private PersonOptionalFields(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static PersonOptionalFields findByValue(int value) { 
    switch (value) {
      case 0:
        return SNILS;
      case 1:
        return MR;
      case 2:
        return OKATOG;
      case 3:
        return OKATOP;
      case 4:
        return FAM_P;
      case 5:
        return IM_P;
      case 6:
        return OT_P;
      case 7:
        return DR_P;
      case 8:
        return W_P;
      default:
        return null;
    }
  }
}
